# -*- coding: utf-8 -*-
"""resume&portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZ4ews5KQCEI78MheRZJ-w4hcgF18dTp

**Define Student Profile Data Structure**
"""

class StudentProfile:
    def __init__(self, name, education, skills, experience, projects):
        self.name = name
        self.education = education
        self.skills = skills
        self.experience = experience
        self.projects = projects

    def __repr__(self):
        return f"StudentProfile(name='{self.name}', education='{self.education}', skills='{self.skills}', experience='{self.experience}', projects='{self.projects}')"

print("StudentProfile class defined.")

"""**Create Sample Student Data**"""

sample_name = "Alice Smith"
sample_education = "Master of Science in Data Science, University of Example (2023)"
sample_skills = [
    "Python",
    "SQL",
    "Machine Learning (Scikit-learn, TensorFlow, PyTorch)",
    "Deep Learning",
    "Data Visualization (Matplotlib, Seaborn)",
    "Cloud Computing (AWS, GCP)"
]
sample_experience = [
    "Data Scientist Intern at Tech Innovations Inc. (Summer 2022): Developed predictive models for customer churn.",
    "Research Assistant at University of Example (2021-2023): Analyzed large datasets for bioinformatics project."
]
sample_projects = [
    "Sentiment Analysis of Social Media Data: Built a deep learning model to classify sentiment.",
    "E-commerce Recommendation System: Implemented a collaborative filtering algorithm."
]

sample_student = StudentProfile(
    name=sample_name,
    education=sample_education,
    skills=sample_skills,
    experience=sample_experience,
    projects=sample_projects
)

print("Sample student profile created and stored in 'sample_student'.")

"""
 Basic Resume Section"""

def generate_skills_section(student_profile):
    """
    Generates a formatted string for the skills section of a resume.

    Args:
        student_profile (StudentProfile): An object containing student profile data.

    Returns:
        str: A formatted string representing the skills section.
    """
    if not student_profile.skills:
        return "Skills: None listed."

    # Join skills with commas for a readable list
    formatted_skills = "Skills: " + ", ".join(student_profile.skills)
    return formatted_skills

# Generate the skills section using the sample student data
skills_section = generate_skills_section(sample_student)

# Print the generated section to verify
print(skills_section)

"""**Prepare Student Data for Generative AI**"""

def create_llm_prompt_from_profile(student_profile):
    """
    Transforms a StudentProfile object into a text-based prompt suitable for an LLM.

    Args:
        student_profile (StudentProfile): An object containing student profile data.

    Returns:
        str: A formatted multi-line string representing the student's profile as an LLM prompt.
    """
    prompt_parts = []

    prompt_parts.append(f"Student Name: {student_profile.name}")
    prompt_parts.append(f"Education: {student_profile.education}")

    if student_profile.skills:
        prompt_parts.append("Skills:")
        for skill in student_profile.skills:
            prompt_parts.append(f"- {skill}")

    if student_profile.experience:
        prompt_parts.append("Experience:")
        for exp in student_profile.experience:
            prompt_parts.append(f"- {exp}")

    if student_profile.projects:
        prompt_parts.append("Projects:")
        for project in student_profile.projects:
            prompt_parts.append(f"- {project}")

    return "\n".join(prompt_parts)

# Generate the LLM prompt using the sample student data
llm_prompt = create_llm_prompt_from_profile(sample_student)

# Print the generated prompt to verify its structure and content
print("--- Generated LLM Prompt ---")
print(llm_prompt)
print("----------------------------")

"""**Implement AI-Powered Resume Generation**"""

def mock_llm_generate(prompt):
    """
    A mock Large Language Model function that simulates an LLM response.
    """
    return f"[Mock LLM Response]\nBased on your request, I generated the following content:\n\nPrompt: '{prompt}'\n\n[End Mock LLM Response]"

print("Mock LLM function 'mock_llm_generate' defined.")

"""**Implement AI-Powered Cover Letter Generation**"""

def generate_ai_cover_letter(student_profile, mock_llm_function, job_description=None):
    """
    Generates a personalized cover letter using a mock LLM based on student profile data
    and an optional job description.

    Args:
        student_profile (StudentProfile): An object containing student profile data.
        mock_llm_function (function): The mock LLM function to generate text.
        job_description (str, optional): A description of the job to tailor the cover letter to. Defaults to None.

    Returns:
        str: A generated cover letter.
    """
    # Use the existing function to get a base profile description
    base_prompt = create_llm_prompt_from_profile(student_profile)

    # Add instructions for cover letter generation
    cover_letter_instruction = (
        "\n\nBased on the above student profile, generate a professional, personalized cover letter. "
        "The letter should be 3-5 paragraphs long, highlight key skills and experiences relevant to a data science role, "
        "and demonstrate the student's enthusiasm and fit for the position."
    )

    if job_description:
        cover_letter_instruction += (
            f"\n\nTailor the cover letter specifically to the following job description: "
            f"\n\"\"\"{job_description}\"\"\"" # Triple quotes to handle multi-line descriptions
            "\nEnsure that the cover letter clearly addresses the requirements and responsibilities mentioned in the job description."
        )

    cover_letter_instruction += "\n\nBegin the cover letter with 'Dear Hiring Manager,' and end with 'Sincerely, Alice Smith.'"

    full_prompt = base_prompt + cover_letter_instruction
    return mock_llm_function(full_prompt)

print("'generate_ai_cover_letter' function defined.")

"""**Implement AI-Powered Portfolio Content Suggestions**"""

def generate_ai_portfolio_project_description(student_profile, project_description, mock_llm_function):
    """
    Generates a descriptive text for a project suitable for an online portfolio using a mock LLM.

    Args:
        student_profile (StudentProfile): An object containing student profile data.
        project_description (str): A single project description string from the student's projects list.
        mock_llm_function (function): The mock LLM function to generate text.

    Returns:
        str: Generated descriptive text for the project.
    """
    # Use the existing function to get a base profile description for context
    base_prompt = create_llm_prompt_from_profile(student_profile)

    # Add instructions for generating a detailed project description
    project_instruction = (
        f"\n\nBased on the following project description and the student's overall profile, "
        f"generate a detailed descriptive text for an online portfolio for the project: "
        f"'{project_description}'.\n\n"
        "The description should be 2-3 paragraphs or 3-5 accomplishment-driven bullet points. "
        "Highlight the problem addressed, the methodologies and technologies used (drawing from the student's skills), "
        "the solution implemented, and the quantifiable impact or outcome of the project. "
        "Ensure the generated content is professional and engaging for potential employers."
    )

    full_prompt = base_prompt + project_instruction
    return mock_llm_function(full_prompt)

print("'generate_ai_portfolio_project_description' function defined.")


print("\n--- Generating AI-powered Portfolio Project Description ---")
# Choose one project item from sample_student
project_item = sample_student.projects[0] # Taking the first project item
ai_portfolio_description = generate_ai_portfolio_project_description(sample_student, project_item, mock_llm_generate)
print(ai_portfolio_description)

print("\nDemonstrated AI-powered portfolio project description generation.")

"""Format Comprehensive Output

"""

def assemble_full_document(student_profile, mock_llm_function, job_description=None):
    """
    Assembles a comprehensive document combining AI-generated resume sections, cover letter,
    and portfolio content.

    Args:
        student_profile (StudentProfile): An object containing student profile data.
        mock_llm_function (function): The mock LLM function to generate text.
        job_description (str, optional): A description of the job to tailor the cover letter to.

    Returns:
        str: A formatted string representing the complete document.
    """
    full_document_parts = []

    full_document_parts.append("# Comprehensive AI-Generated Professional Document\n")
    full_document_parts.append(f"## Student: {student_profile.name}\n")

    # Generate Resume Summary
    summary = generate_ai_summary(student_profile, mock_llm_function)
    full_document_parts.append("### Resume Summary\n")
    full_document_parts.append(summary + "\n")

    # Generate Accomplishment Bullets for first Experience item
    if student_profile.experience:
        experience_item_to_process = student_profile.experience[0]
        accomplishment_bullet_exp = generate_ai_accomplishment_bullet(student_profile, experience_item_to_process, mock_llm_function)
        full_document_parts.append("### Enhanced Experience Bullet Point\n")
        full_document_parts.append(f"*Original: {experience_item_to_process}*\n")
        full_document_parts.append(accomplishment_bullet_exp + "\n")

    # Generate Accomplishment Bullets for first Project item
    if student_profile.projects:
        project_item_to_process = student_profile.projects[0]
        accomplishment_bullet_proj = generate_ai_accomplishment_bullet(student_profile, project_item_to_process, mock_llm_function)
        full_document_parts.append("### Enhanced Project Bullet Point\n")
        full_document_parts.append(f"*Original: {project_item_to_process}*\n")
        full_document_parts.append(accomplishment_bullet_proj + "\n")

    # Generate Cover Letter (without job description)
    cover_letter_no_jd = generate_ai_cover_letter(student_profile, mock_llm_function)
    full_document_parts.append("### Cover Letter (General)\n")
    full_document_parts.append(cover_letter_no_jd + "\n")

    # Generate Cover Letter (with job description)
    if job_description:
        cover_letter_with_jd = generate_ai_cover_letter(student_profile, mock_llm_function, job_description)
        full_document_parts.append("### Cover Letter (Tailored to Job Description)\n")
        full_document_parts.append(f"*Job Description: {job_description[:100]}...*\n") # Truncate for display
        full_document_parts.append(cover_letter_with_jd + "\n")

    # Generate Portfolio Project Description for first project
    if student_profile.projects:
        portfolio_project_description = generate_ai_portfolio_project_description(student_profile, project_item_to_process, mock_llm_function)
        full_document_parts.append("### Portfolio Project Description\n")
        full_document_parts.append(f"*For Project: {project_item_to_process}*\n")
        full_document_parts.append(portfolio_project_description + "\n")

    return "\n".join(full_document_parts)


print("'assemble_full_document' function defined.")

# Call the function and print the full document
print("\n--- Assembling Full AI-Generated Document ---")
full_document = assemble_full_document(sample_student, mock_llm_generate, sample_job_description)
print(full_document)
print("---------------------------------------------")

sample_job_description = (
    "We are seeking a highly motivated and skilled Data Scientist to join our team. "
    "The ideal candidate will have a strong background in machine learning, statistical modeling, "
    "and data visualization. Responsibilities include developing predictive models, "
    "analyzing large datasets, and presenting findings to stakeholders. "
    "Proficiency in Python, SQL, and cloud platforms (AWS, GCP) is required."
)
print("Sample job description defined.")

def assemble_full_document(student_profile, mock_llm_function, job_description=None):
    """
    Assembles a comprehensive document combining AI-generated resume sections, cover letter,
    and portfolio content.

    Args:
        student_profile (StudentProfile): An object containing student profile data.
        mock_llm_function (function): The mock LLM function to generate text.
        job_description (str, optional): A description of the job to tailor the cover letter to.

    Returns:
        str: A formatted string representing the complete document.
    """
    full_document_parts = []

    full_document_parts.append("# Comprehensive AI-Generated Professional Document\n")
    full_document_parts.append(f"## Student: {student_profile.name}\n")

    # Generate Resume Summary
    # Assuming generate_ai_summary is defined elsewhere or will be defined
    # For now, let's use a mock or placeholder if it's not crucial for this step
    try:
        summary = generate_ai_summary(student_profile, mock_llm_function)
    except NameError:
        summary = "[Mock Summary: A highly skilled data scientist with experience in ML and deep learning.]"
    full_document_parts.append("### Resume Summary\n")
    full_document_parts.append(summary + "\n")

    # Generate Accomplishment Bullets for first Experience item
    if student_profile.experience:
        experience_item_to_process = student_profile.experience[0]
        try:
            accomplishment_bullet_exp = generate_ai_accomplishment_bullet(student_profile, experience_item_to_process, mock_llm_function)
        except NameError:
            accomplishment_bullet_exp = f"[Mock Accomplishment for Experience: {experience_item_to_process}]"
        full_document_parts.append("### Enhanced Experience Bullet Point\n")
        full_document_parts.append(f"*Original: {experience_item_to_process}*\n")
        full_document_parts.append(accomplishment_bullet_exp + "\n")

    # Generate Accomplishment Bullets for first Project item
    if student_profile.projects:
        project_item_to_process = student_profile.projects[0]
        try:
            accomplishment_bullet_proj = generate_ai_accomplishment_bullet(student_profile, project_item_to_process, mock_llm_function)
        except NameError:
            accomplishment_bullet_proj = f"[Mock Accomplishment for Project: {project_item_to_process}]"
        full_document_parts.append("### Enhanced Project Bullet Point\n")
        full_document_parts.append(f"*Original: {project_item_to_process}*\n")
        full_document_parts.append(accomplishment_bullet_proj + "\n")

    # Generate Cover Letter (without job description)
    cover_letter_no_jd = generate_ai_cover_letter(student_profile, mock_llm_function)
    full_document_parts.append("### Cover Letter (General)\n")
    full_document_parts.append(cover_letter_no_jd + "\n")

    # Generate Cover Letter (with job description)
    if job_description:
        cover_letter_with_jd = generate_ai_cover_letter(student_profile, mock_llm_function, job_description)
        full_document_parts.append("### Cover Letter (Tailored to Job Description)\n")
        full_document_parts.append(f"*Job Description: {job_description[:100]}...*\n") # Truncate for display
        full_document_parts.append(cover_letter_with_jd + "\n")

    # Generate Portfolio Project Description for first project
    if student_profile.projects:
        portfolio_project_description = generate_ai_portfolio_project_description(student_profile, project_item_to_process, mock_llm_function)
        full_document_parts.append("### Portfolio Project Description\n")
        full_document_parts.append(f"*For Project: {project_item_to_process}*\n")
        full_document_parts.append(portfolio_project_description + "\n")

    return "\n".join(full_document_parts)


print("'assemble_full_document' function defined.")

# Call the function and print the full document
print("\n--- Assembling Full AI-Generated Document ---")
full_document = assemble_full_document(sample_student, mock_llm_generate, sample_job_description)
print(full_document)
print("---------------------------------------------")